name: AdvancedPunishments
version: ${project.version}
main: me.mrkornel.advancedpunishments.AdvancedPunishments
authors: [MrKornel]
description: punishemtns
commands:
  pkick:
    usage: /pkick <player> <reason>
  pban:
    usage: /pban <player> <reason> <time>
  preload:
    usage: /preload
    aliases: /prl
  phelp:
    usage: /phelp
  puban:
    usage: /puban <player>
  pmute:
    usage: /pmute <player> <reason> <time>
  punmute:
    usage: /punmute <player>
permissions:
  advancedpunishments.ban:
    default: op
    description: /pban permission
  advancedpunishments.kick:
      default: op
      description: /pkick permission
  advancedpunishments.unban:
    default: op
    description: /puban permission
  advancedpunishments.unmute:
    default: op
    description: /punmute permission
  advancedpunishments.help:
    default: op
    description: /phelp permission
